---
title: Caesar Mukama
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Making the web great.

'
baseurl: ''
url: http://mukama.github.io
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
- assets/sass
gems:
- jekyll-feed
- jekyll-sitemap
